/**
 * Dependency modules
 */
import {Link} from "react-router-dom";


/**
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import '../scss/main.css';
/* Import of the images for this component */
import logo from '../images/logo-no-background.png';

/**
 * Definition of the navigation header component that will appear at the top of all renders
 */
export const Header = () => {
    return (
        <div className={'header-container'}>
            <div className={'header-top'}>
                <div className={'header-logo'}>
                    <Link
                        to={'/'}>
                        <img className={'header-logo_img'} src={logo} alt={'Cool Tech Logo'}/>
                    </Link>
                </div>
                <div className={'header-title'}>
                    <h1>Cool Tech</h1>
                </div>
            </div>
        </div>
    )
}