/**
 * Import of other components needed
 */
import {NavigationBar} from "./NavigationBar";
import {Header} from "./Header";

/**
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import '../scss/main.css';
/* Import of images needed in this component */
import logo from '../images/logo-no-background.png';

/**
 * Definition of the home page component that users can return to as a base point during their
 * time in the application
 */
export const Home = () => {

    return (
        <div>
            <Header/>
            <NavigationBar/>
            <div className={'home-wrapper'}>
                <div className={'home-container'}>
                    <div className={'home-logo'}>
                        <img src={logo} classname={'home-logo'} alt="Cool Tech Logo"/>
                    </div>
                    <h1 className={'home-title'}>Credential Authentication System</h1>
                </div>
            </div>
        </div>
    )
}