/**
* Import of components needed in this component
*/
import {Link} from "react-router-dom";

/**
* Import of the main stylesheet generated by the SCSS files and preprocessor
*/
import '../scss/main.css';
/* Import of images needed in this component */
import logo from '../images/logo-no-background.png';

/**
 * Definition of the landing page component that will greet users upon navigating to the application
 */
export const LandingPage = () => {

    return (
        <div className={'landing-container'}>
            <div className={'landing-logo'}>
                <img src={logo} className={'landing-page-logo'} alt="Cool Tech Logo"/>
            </div>
            <h1 className={'landing-title'}>Credential Authentication System</h1>
            <h2 className={'landing-subtitle'}>Please login or register before proceeding</h2>
            <div className={'landing-access_btn'}>
                <Link to={'/login'}>
                    <button className={'btn-login'}>
                        Login
                    </button>
                </Link>
                <Link to={'/registration'}>
                    <button className={'btn-register'}>
                        Register
                    </button>
                </Link>
            </div>
        </div>
    )
}