/**
 * Dependency modules and hooks
 */
import {Link} from 'react-router-dom';
import {useEffect} from 'react';

/**
 * Import of components referenced in this function
 */
import {Header} from "./Header";

/**
 * Import of the main stylesheet generated by SCSS files and preprocessor
 */
import '../scss/main.css';

export const LogoutFeedback = () => {

    /* Removal of the JWT token from local storage upon logout */
    useEffect(() => {

        localStorage.removeItem('JWT token');

    }, [])

    /* Rendering of successful logout page and some navigation instructions */
    return (

        <div className={'logout-feedback'}>
            <Header/>
            <div className={'logout-feedback-container'}>
                <div className={'feedback-container__message'}>
                    <div>
                        <h1 className={'primary-message success'}>Successfully Logged out</h1>
                        <h2 className={'secondary-message'}>Please click on the button to log back in</h2>
                        <h2 className={'secondary-message'}>or on the logo to return home</h2>
                    </div>
                </div>
                <div className={'feedback-container__btn'}>
                    <Link
                        to={'/login'}
                        className={'logout-link'}
                    >
                        <button className={'btn-register'}>
                            Login
                        </button>
                    </Link>
                </div>
            </div>
        </div>
    )
};