/**
 * Dependency modules and hooks
 */
import {useState, useEffect} from "react";
import axios from 'axios';

/**
 * Import of other components needed
 */
import {Header} from "./Header";
import {NavigationBar} from "./NavigationBar";

/**
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import '../scss/main.css';
/* Import of Styled React Bootstrap Table */
import Table from 'react-bootstrap/Table';
import Spinner from 'react-bootstrap/Spinner';

export const ViewCredentialRepo = () => {

    /* Declaring and initialising state variable */
    const [isLoading, setIsLoading] = useState(false);

    /* Declaration of the array used for rendering the table data of the credential repos */
    const [userDiscreteCredentials, setUserDiscreteCredentials] = useState([]);

    /*
     * useEffect hook to run the axios call to the backend once to get the credential repo info that
     * needs to be displayed on this page
     */
    useEffect(() => {

        setIsLoading(true);

        /* Acquiring the JWT token from localStorage */
        const token = localStorage.getItem('JWT token')

        /* Axios configuration parameters */
        const apiUrl = 'http://localhost:8000/api/view-credentials';
        const config = {
            headers: {
                Authorization: 'Bearer ' + token
            }
        }

        /* Axios call to the backend endpoint 'view-credentials' */
        axios.get(apiUrl, config)
            .then(response => {
                setUserDiscreteCredentials(response.data)
                setIsLoading(false);
            })
            .catch(error => {

                console.log(error)

            })

    }, []);

    return (
        <div className={'view-credentials-wrapper'}>
            <Header/>
            <NavigationBar/>
            {isLoading ?
                <div className={'spinner-container'}>
                    <Spinner className={'mx-auto mt-5 spinner'} animation="border" variant='light'/>
                </div> :
                <div className={'card'}>
                    <Table
                        striped
                        bordered
                        hover
                        responsive
                        className={'mt-5'}
                    >
                        <thead>
                        <tr>
                            <th
                                colSpan="5"
                                className={'view-credentials-table_heading h2 fw-bold text-center'}
                            >
                                Authorised Credential Repos
                            </th>
                        </tr>
                        <tr>
                            <th className={'h4 fw-bold'}>Organisational Unit</th>
                            <th className={'h4 fw-bold'}>Division</th>
                            <th className={'h4 fw-bold'}>Resource</th>
                            <th className={'h4 fw-bold'}>Username</th>
                            <th className={'h4 fw-bold'}>Password</th>
                            <th className={'h4 fw-bold'}></th>
                        </tr>
                        </thead>
                        <tbody>
                        {userDiscreteCredentials.map((resource, index) => {
                            return (
                                <tr key={index}>
                                    <td className={'h5'}>{resource.organisationalUnitName}</td>
                                    <td className={'h5'}>{resource.divisionName}</td>
                                    <td className={'h5'}>{resource.resource}</td>
                                    <td className={'h5'}>{resource.username}</td>
                                    <td className={'h5'}>{resource.password}</td>
                                    <td className={'h5'}>

                                    </td>
                                </tr>
                            )
                        })}
                        </tbody>
                    </Table>
                </div>
            }
        </div>
    );
}
