/**
 * Dependency modules
 */
import {Routes, Route} from "react-router-dom";

/**
 * Import of the components needed in this module
 */
import {LandingPage} from "./components/LandingPage";
import {Registration} from "./components/Registration";
import {RegistrationFeedback} from "./components/RegistrationFeedback";

/**
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import './scss/main.css';
import {Login} from "./components/Login";

/**
 * Definition of the main App component that is mainly used to handle routing
 * @returns {JSX.Element}
 */
export const App = () => {
    return (
        <div className="App">
            <Routes>
                <Route path={'/'} element={<LandingPage/>} exact/>
                <Route path={'/registration'} element={<Registration/>}/>
                <Route path={'/login'} element={<Login/>}/>
                <Route path={'/registrationFeedback'} element={<RegistrationFeedback/>}/>
            </Routes>
        </div>
    );
}

