/*
 * Dependency modules
 */
import {Routes, Route} from "react-router-dom";

/*
 * Import of the components needed in this module
 */


/*
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import './scss/main.css';

export const App = () => {
  return (
    <div className="App">
      <Routes>

      </Routes>
    </div>
  );
}

