/*
 * Dependency modules
 */
import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from "react-router-dom";

/*
 * Import of the main App module rendered in index.js
 */
import {App} from './App';

/*
 * Import of the main stylesheet generated by the SCSS files and preprocessor
 */
import './scss/main.css';

/*
 * Rendering of the main App component in the div with id 'root' in index.html. The main router is also set up
 * here by wrapping it around the App component. The separate routes are set up in App.js
 */
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <App/>
        </BrowserRouter>
    </React.StrictMode>
);

